export const TOTAL_BALANCE = "TOTAL_BALANCE";
export const SPENDING_LIMIT = "SPENDING_LIMIT";
export const SET_SPENDING_LIMIT = "SET_SPENDING_LIMIT";
export const SAVE_BALANCE = "SAVE_BALANCE";
export const SAVE_SPENDING_LIMIT = "SAVE_SPENDING_LIMIT";
export const CARD_DETAIL = "CARD_DETAIL";
export const SAVE_CARD_DETAIL = "SAVE_CARD_DETAIL";
